### PR TITLE
Responsive_Design Project No. 6 Replica of "The Next Web" official page.

### PR DESCRIPTION
**Pull request by mariosknl**
We replicated the official "The Next Web" website and we added 4 breakpoints. This webpage consists of 2 navigation bars and 5 different sections and 2 footer sections. There 4 different media queries each one for the 4 breakpoints.  Media queries made for: 1) max-width: 767px, 2) max-width: 1023px, 3) min-width: 1024px 4) min-width: 1440px.

### CODE REVIEW

**Review by rOluochKe — CHANGES_REQUESTED** [review]
Hello @mariosknl and @sddoe 
### You have done a good so far, however, there are a few changes you need to make before your project can be approved.
- Avoid using inline css in your html code, they all should be put in css file
- Add more padding to the left and right of the main content to resemble reference [website](https://thenextweb.com/)
- Fix the horizontal scrollbar, not needed
-  Your text overflow when I check on the different devices need fixing
- Some of the images disappear on different screen sizes

### Fix all these changes and resubmit for another review. Good luck!
- Happy coding!
- For assistance: contact me on @rOluochKe

**Comment by izaiasneto4** [comment]
### Hi @mariosknl and @sddoe. Great job implementing the requested changes :+1: , let's just fix a few more things in order to get your project approved :arrow_down: 

- [x] This section is being overlayed in your mobile/tablet version, let's fix this
image

Please, when finished with the changes submit your project for a new review :pray: 

TSE: Izaias Neto

**Comment by sddoe** [comment]
Fixed sections which were overlayed in the mobile/tablet version

**Review by mosesogwo — CHANGES_REQUESTED** [review]
### Hi team, you have a great project:+1:, but we still need to take care of these:

1. The Latest News section overflows into each other on medium screen sizes - check around 824px

image

2. The Latest Funding section should be aligned 3 per row on medium screen sizes.

**Optional:** Group your css files in a folder.

_**Kindly make these changes and submit for another review**_

**Cheers:smile:**

### Status: Changes requested

**Comment by sddoe** [comment]
Fixed overflows errors, modify Latest Funding Section on medium screen sizes, put css files in one file

**Review by mosesogwo — APPROVED** [review]
### :trophy:Congratulations. You can now merge to master :heavy_check_mark:.

### Status: Approved.

**Pull request merged**
